# Comic, Manga and eBook containers

# Kapowarr: Comic manager and downloader
# Komga: Comic server
# Kaizoku: Manga downloader
# Redis: Kaizoku dependency
# Kaizoku-db: Kaizoku dependency
# Readarr: Ebook downloader

version: "2.1"

volumes:
  db:
  redis:

services:
  kapowarr:
    container_name: kapowarr
    restart: always
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKER_PATH/kapowarr/kapowarr-db:/app/db
      - $DOCKER_PATH/kapowarr/temp_downloads:/app/temp_downloads
      - $MEDIA_PATH/comics:/content
    ports:
      - "5656:5656"
    image: "mrcas/kapowarr:latest"

  komga:
    image: gotson/komga:1.3.1
    container_name: komga
    volumes:
      - $DOCKER_PATH/komga:/config
      - $MEDIA_PATH/comics:/comics
      - $MEDIA_PATH/manga:/manga
      - $USB_PATH:/data
    ports:
      - 25600:25600
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    restart: unless-stopped

  kaizoku:
    container_name: kaizoku
    image: ghcr.io/oae/kaizoku:latest
    environment:
      - DATABASE_URL=postgresql://kaizoku:kaizoku@kaizoku-db:5432/kaizoku
      - KAIZOKU_PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $MEDIA_PATH/manga:/manga
      - $DOCKER_PATH/kaizoku/config:/config
      - $DOCKER_PATH/kaizoku/logs:/logs
    depends_on:
      kaizoku-db:
        condition: service_healthy
    ports:
      - "3000:3000"

  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data

  kaizoku-db:
    image: postgres:15-alpine
    container_name: kaizoku-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kaizoku"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=kaizoku
      - POSTGRES_DB=kaizoku
      - POSTGRES_PASSWORD=kaizoku
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - db:/var/lib/postgresql/data

  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKER_PATH/readarr:/config
      - $MEDIA_PATH/books:/books
      - $USB_PATH:/data
    ports:
      - 8787:8787
    restart: unless-stopped
