# Download clients

# Sabnzbd: usenet download client

version: "2.1"

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKER_PATH/sabnzbd:/config
      - $USENET_PATH/incomplete:/data/usenet/incomplete
      - $USENET_PATH/completed:/data/usenet/completed
    ports:
      - 8080:8080
    restart: unless-stopped
