# Miscellaneous docker containers

# Code server: Hosted VS Code
# Ntfy: Notification server

version: "2.1"

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - $DOCKER_PATH/vscode:/config
    ports:
      - 8443:8443
    restart: unless-stopped

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - NTFY_BASE_URL=https://ntfy.olly.live
      - NTFY_CACHE_FILE=/var/lib/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_BEHIND_PROXY=true
      - NTFY_ATTACHMENT_CACHE_DIR=/var/lib/ntfy/attachments
      - NTFY_ENABLE_LOGIN=true
      - NTFY_UPSTREAM_BASE_URL=https://ntfy.sh
      - NTFY_WEB_PUSH_PUBLIC_KEY=${NTFY_WEB_PUSH_PUBLIC_KEY}
      - NTFY_WEB_PUSH_PRIVATE_KEY=${NTFY_WEB_PUSH_PRIVATE_KEY}
      - NTFY_WEB_PUSH_FILE=/var/lib/ntfy/webpush.db
      - NTFY_WEB_PUSH_EMAIL_ADDRESS=${NTFY_WEB_PUSH_EMAIL_ADDRESS}
      - TZ=${TZ}
    volumes:
      - $DOCKER_PATH/ntfy/cache:/var/cache/ntfy:rw
      - $DOCKER_PATH/ntfy:/etc/ntfy:rw
    ports:
      - 38158:80
    restart: unless-stopped
