# Docker images for managing music
# Music is served with Plex (See docker-compose.shows-movies.yml)

# Soulseek: Music downloader
# Lidarr: Music collection manager

version: "2.1"

services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKER_PATH/lidarr:/config
      - $MEDIA_PATH/music:/music
      - $USB_PATH:/data
    ports:
      - 8686:8686
    restart: unless-stopped
