# Network config containers

# Nginx Proxy Manager: Reverse Proxy manager
# MariaDB: Database for Nginx Proxy Manager
# PiHole: DNS server with adblocker

version: "2.1"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "47975:80/tcp"
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
      ServerIP: $SERVERIP
      DNSMASQ_USER: root
      WEBPASSWORD: $WEBPASSWORD
    volumes:
      - $DOCKER_PATH/pihole/pihole:/etc/pihole
      - $DOCKER_PATH/pihole/dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
