version: "2.1"

include:
  - path: "docker-compose-files/docker-compose.books-comics.yml"
  - path: "docker-compose-files/docker-compose.dl-clients.yml"
  - path: "docker-compose-files/docker-compose.meta.yml"
  - path: "docker-compose-files/docker-compose.minecraft.yml"
  - path: "docker-compose-files/docker-compose.misc.yml"
  - path: "docker-compose-files/docker-compose.music.yml"
  - path: "docker-compose-files/docker-compose.networking.yml"
  - path: "docker-compose-files/docker-compose.shows-movies.yml"
